// modules/help/viewmodels/faq.viewmodel.ts
// FAQ ViewModel - mostly static data, but keeping pattern consistent

export interface FAQItem {
  question: string
  answer: string
}

export function useFAQViewModel() {
  const faqs: FAQItem[] = [
    {
      question: "How does YIFY Lending work?",
      answer: "YIFY allows you to borrow USDC against your productive NFTs (veNFTs & RWA). The yield generated by your NFTs is used to automatically repay the loan over time. There are no monthly payments."
    },
    {
      question: "What is the LTV ratio?",
      answer: "LTV (Loan-to-Value) is calculated based on the projected yield of your asset over 65 weeks. The formula is MIN(50%, Projection_Yield × 65). This ensures the loan can be repaid by yield alone."
    },
    {
      question: "Is there a risk of liquidation?",
      answer: "No. Since the loan is repaid by yield and LTV is conservative, there is no liquidation mechanism based on price fluctuation. Your asset is safe as long as it generates yield."
    },
    {
      question: "What happens if I don't repay in 65 weeks?",
      answer: "If the yield wasn't enough to cover the loan in 65 weeks, the loan period is automatically extended. You can also manually repay the remaining balance at any time."
    }
  ]

  return {
    faqs
  }
}

