import React, { useState } from 'react'
import { ChevronDown, HelpCircle, AlertTriangle, MessageCircle } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

const FAQItem = ({ question, answer }: { question: string, answer: string }) => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div className="border-4 border-black bg-white shadow-neo mb-4">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-6 py-4 flex items-center justify-between text-left font-bold hover:bg-gray-50 transition-colors"
      >
        <span className="text-lg uppercase">{question}</span>
        <ChevronDown 
          className={`w-6 h-6 transition-transform border-2 border-black rounded-full ${isOpen ? 'rotate-180 bg-neo-yellow' : ''}`} 
        />
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="px-6 py-4 border-t-4 border-black bg-gray-50 font-medium">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

const HelpFAQ: React.FC = () => {
  const faqs = [
    {
      question: "How does YIFY Lending work?",
      answer: "YIFY allows you to borrow USDC against your productive NFTs (veNFTs & RWA). The yield generated by your NFTs is used to automatically repay the loan over time. There are no monthly payments."
    },
    {
      question: "What is the LTV ratio?",
      answer: "LTV (Loan-to-Value) is calculated based on the projected yield of your asset over 65 weeks. The formula is MIN(50%, Projection_Yield × 65). This ensures the loan can be repaid by yield alone."
    },
    {
      question: "Is there a risk of liquidation?",
      answer: "No. Since the loan is repaid by yield and LTV is conservative, there is no liquidation mechanism based on price fluctuation. Your asset is safe as long as it generates yield."
    },
    {
      question: "What happens if I don't repay in 65 weeks?",
      answer: "If the yield wasn't enough to cover the loan in 65 weeks, the loan period is automatically extended. You can also manually repay the remaining balance at any time."
    }
  ]

  return (
    <div className="max-w-4xl mx-auto space-y-12">
      <div className="text-center space-y-4">
        <h1 className="text-5xl font-black uppercase">Help Center</h1>
        <p className="text-xl font-bold text-gray-600">Got questions? We've got answers.</p>
      </div>

      <div className="grid gap-8">
        <section>
          <div className="flex items-center gap-4 mb-6">
            <div className="p-3 bg-neo-cyan border-4 border-black shadow-neo">
              <HelpCircle size={32} />
            </div>
            <h2 className="text-3xl font-black uppercase">Frequently Asked Questions</h2>
          </div>
          <div>
            {faqs.map((faq, index) => (
              <FAQItem key={index} {...faq} />
            ))}
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="card-neo bg-neo-yellow">
            <div className="flex items-center gap-3 mb-4">
              <AlertTriangle size={24} />
              <h3 className="text-xl font-black uppercase">Risk Disclosure</h3>
            </div>
            <p className="font-bold mb-4">
              While we minimize risks, DeFi protocols always carry some inherent risks including smart contract bugs and systemic failures.
            </p>
            <button className="btn-neo text-sm w-full">Read Full Disclosure</button>
          </div>

          <div className="card-neo bg-neo-lime">
            <div className="flex items-center gap-3 mb-4">
              <MessageCircle size={24} />
              <h3 className="text-xl font-black uppercase">Support</h3>
            </div>
            <p className="font-bold mb-4">
              Need direct assistance? Our support team is available 24/7 on Discord and Telegram.
            </p>
            <button className="btn-neo text-sm w-full">Contact Support</button>
          </div>
        </section>
      </div>
    </div>
  )
}

export default HelpFAQ

